[package]
name = "orange-zest"
version = "0.1.0"
authors = ["Cldfire"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "0.11"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
